#header
name: overlander.family
description: Familie ZÃ¼ger unterwegs
favicon: /fav.png
ga: ''

#nav
nav:
    HOME: /
    ARCHIV: /archives/
    # GALLERY:  /gallery/
    # ABOUT: /about/

#post
excerpt_link: Weiterlesen...


#about me
aboutMeImg: /about_me.jpg

github: https://github.com/mzueger
instagram: https://instagram.com/uyarak

#copyright
themeLink: https://github.com/yiliashaw/hexo-theme-prince

